export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const REFRESH_TOKEN_REQUESTED = 'REFRESH_TOKEN_REQUESTED';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAILED = 'REFRESH_TOKEN_FAILED';

export const GET_PROFILE_REQUESTED = 'GET_PROFILE_REQUESTED';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILED = 'GET_PROFILE_FAILED';

export const CREATE_PROFILE_REQUESTED = 'CREATE_PROFILE_REQUESTED';
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS';
export const CREATE_PROFILE_FAILED = 'CREATE_PROFILE_FAILED';

export const UPDATE_PROFILE_REQUESTED = 'UPDATE_PROFILE_REQUESTED';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED';

export const GET_SITUATION_REQUESTED = 'GET_SITUATION_REQUESTED';
export const GET_SITUATION_SUCCESS = 'GET_SITUATION_SUCCESS';
export const GET_SITUATION_FAILED = 'GET_SITUATION_FAILED';

export const GET_SITUATION_AVAILABLE_REQUESTED = 'GET_SITUATION_AVAILABLE_REQUESTED';
export const GET_SITUATION_AVAILABLE_SUCCESS = 'GET_SITUATION_AVAILABLE_SUCCESS';
export const GET_SITUATION_AVAILABLE_FAILED = 'GET_SITUATION_AVAILABLE_FAILED';

export const GET_SITUATIONS_REQUESTED = 'GET_SITUATIONS_REQUESTED';
export const GET_SITUATIONS_SUCCESS = 'GET_SITUATIONS_SUCCESS';
export const GET_SITUATIONS_FAILED = 'GET_SITUATIONS_FAILED';


export const CREATE_SITUATION_REQUESTED = 'CREATE_SITUATION_REQUESTED';
export const CREATE_SITUATION_SUCCESS = 'CREATE_SITUATION_SUCCESS';
export const CREATE_SITUATION_FAILED = 'CREATE_SITUATION_FAILED';

export const UPDATE_SITUATION_REQUESTED = 'UPDATE_SITUATION_REQUESTED';
export const UPDATE_SITUATION_SUCCESS = 'UPDATE_SITUATION_SUCCESS';
export const UPDATE_SITUATION_FAILED = 'UPDATE_SITUATION_FAILED';